# Generated by Django 2.0.6 on 2018-08-14 19:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_cleanup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Prix')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='members.Saison')),
            ],
        ),
        migrations.RemoveField(
            model_name='licence',
            name='reduction',
        ),
        migrations.AlterField(
            model_name='licence',
            name='saison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='members.Saison'),
        ),
        migrations.AddField(
            model_name='licence',
            name='tarif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='members.Tarif'),
            preserve_default=False,
        ),
    ]
