# Generated by Django 2.0.6 on 2018-08-14 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180814_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='prenom',
        ),
    ]
