# Generated by Django 2.0.6 on 2018-08-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180814_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='autre_club',
            field=models.BooleanField(default=False, verbose_name="J'ai une licence dans un autre club et je souhaite rester licencié dans ce club (remise de 35€)."),
        ),
        migrations.AlterField(
            model_name='licence',
            name='certificat',
            field=models.FileField(help_text='Votre certificat médical doit dater de moins de 1 ans et doit mentionner que vous êtes "aptes à la pratique du roller" et "en compétition" si vous souhaitez faire des compétitions. Si vous le pouvez, scannez le certificat et ajoutez le (formats PDF ou JPEG).', upload_to='certificats', verbose_name='Certificat médical'),
        ),
    ]
