# Generated by Django 2.0.6 on 2018-08-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180818_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default='Chèque', max_length=100)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='licence',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='paiement_info',
        ),
        migrations.AddField(
            model_name='paiement',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='members.Licence'),
        ),
    ]
