# Generated by Django 2.0.6 on 2018-08-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180819_2339'),
    ]

    operations = [
    ]
