# Generated by Django 2.0.6 on 2018-08-19 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180819_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='stripe_charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement', to='pinax_stripe.Charge'),
        ),
    ]
