# Generated by Django 2.0.6 on 2018-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180825_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='nom',
            field=models.CharField(default='', max_length=30, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='prenom',
            field=models.CharField(default='', max_length=150, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licence',
            name='certificat',
            field=models.FileField(blank=True, help_text='Votre certificat médical doit dater de moins de 1 ans et doit mentionner que vous êtes "aptes à la pratique du roller" et "en compétition" si vous souhaitez faire des compétitions (formats PDF, PNG ou JPEG).', null=True, upload_to='certificats', verbose_name='Certificat médical'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='num_licence',
            field=models.CharField(blank=True, help_text='Si vous avez déjà ete licencié et que vous le connaissez', max_length=15, verbose_name='Numéro de licence'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='photo',
            field=models.FileField(blank=True, help_text='(formats PDF, PNG ou JPEG). ', upload_to='photos', verbose_name="Photo d'identité"),
        ),
    ]
