# Generated by Django 2.0.6 on 2018-09-12 11:31

from django.db import migrations

def migrate_names(apps, schema_editor):
    Membre = apps.get_model('members', 'Membre')
    for m in Membre.objects.all():
        m.nom = m.user.last_name
        m.prenom = m.user.first_name
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20180912_1331'),
    ]

    operations = [
        migrations.RunPython(migrate_names),
    ]
