# Generated by Django 2.0.6 on 2018-11-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20180922_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='certificat_valide',
        ),
    ]
