# Generated by Django 2.0.6 on 2019-08-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_licence_certificat_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='num_licence',
            field=models.CharField(blank=True, help_text='Si vous avez déjà ete licencié et que vous le connaissez', max_length=15, verbose_name='Numéro de licence'),
        ),
    ]
