# Generated by Django 2.0.6 on 2019-01-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_licence_certificat_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='members.Licence'),
        ),
    ]
