# Generated by Django 2.0.6 on 2019-08-25 13:51

from django.db import migrations

def copy_num_licence(apps, schema_editor):
    Membre = apps.get_model('members', 'Membre')
    for m in Membre.objects.prefetch_related('licences'):
        l = m.licences.all()
        if len(l):
            m.num_licence = l[0].num_licence
            m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_membre_num_licence'),
    ]

    operations = [
        migrations.RunPython(copy_num_licence),
    ]
