# Generated by Django 2.0.6 on 2019-08-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_copy_num_licence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='num_licence',
        ),
    ]
