# Generated by Django 2.0.6 on 2019-08-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20190825_1834'),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE pinax_stripe_account CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_bankaccount CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_bitcoinreceiver CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_card CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_charge CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_coupon CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_customer CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_event CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_eventprocessingexception CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_invoice CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_invoiceitem CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_plan CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_subscription CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_transfer CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_transferchargefee CASCADE"),
        migrations.RunSQL("DROP TABLE pinax_stripe_useraccount CASCADE"),

    ]
