# Generated by Django 2.0.6 on 2019-08-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20190121_1340'),
        ('members', '0018_paiement_detail'),
    ]

    operations = [
    ]
